# Generated by Django 4.2.27 on 2026-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech4ed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech4edFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='tech4ed/')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='ViewAccess',
        ),
    ]
