# Generated by Django 4.2.27 on 2026-06-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_barangay'),
        ('osca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osca_Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=10, unique=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('extname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('purok', models.CharField(blank=True, max_length=50)),
                ('date_issued', models.DateField(blank=True)),
                ('member_status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE')], max_length=50)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oscabarangay', to='usr.barangay')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oscacategory', to='osca.oscacategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oscastatus', to='osca.oscastatus')),
            ],
        ),
    ]
