
# Generated by Django 4.2.27 on 2026-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osca', '0002_osca_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osca_informations',
            name='extname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='osca_informations',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]

# Generated by Django 4.2.27 on 2026-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osca', '0002_osca_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osca_informations',
            name='extname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='osca_informations',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
