# Generated by Django 4.2.27 on 2026-06-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osca', '0003_alter_osca_informations_extname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osca_informations',
            name='idno',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='osca_informations',
            constraint=models.UniqueConstraint(fields=('lastname', 'firstname', 'middlename'), name='unique_fullname'),
        ),
    ]
