# Generated by Django 4.2.27 on 2026-06-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_id', models.CharField(max_length=15)),
                ('bio_date', models.DateField()),
                ('bio_time', models.TimeField()),
                ('bio_punchstate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_number', models.CharField(max_length=20, null=True, unique=True)),
                ('employee_id', models.CharField(max_length=20, null=True, unique=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('extname', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6)),
                ('civilstatus', models.CharField(blank=True, choices=[('S', 'SINGLE'), ('M', 'MARRIED'), ('SEP', 'SEPERATED'), ('W', 'WIDOWED'), ('WDR', 'WIDOWER')], max_length=15, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=15, null=True)),
                ('bloodtype', models.CharField(blank=True, max_length=15, null=True)),
                ('add_block', models.CharField(blank=True, max_length=50, null=True)),
                ('add_street', models.CharField(blank=True, max_length=50, null=True)),
                ('add_village', models.CharField(blank=True, max_length=50, null=True)),
                ('add_barangay', models.CharField(blank=True, max_length=50, null=True)),
                ('add_municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('add_province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('umid', models.CharField(blank=True, max_length=50, null=True)),
                ('pagibig', models.CharField(blank=True, max_length=50, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=50, null=True)),
                ('philsys', models.CharField(blank=True, max_length=50, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('gsis', models.CharField(blank=True, max_length=50, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='ViewAccess',
        ),
    ]
