# Generated by Django 4.2.27 on 2026-04-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_biometric'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./media'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='extname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
