# Generated by Django 4.2.27 on 2026-04-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_photo_alter_employee_extname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='bio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', to_field='biometric_number'),
        ),
    ]
