# Generated by Django 4.2.27 on 2026-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_position_alter_biometric_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='bio_id',
            field=models.CharField(max_length=15),
        ),
    ]
