# Generated by Django 4.2.27 on 2026-04-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_biometric_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='bio_id',
            field=models.ForeignKey(blank=True, db_column='bio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', to_field='biometric_number'),
        ),
    ]
