# Generated by Django 4.2.27 on 2026-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_biometric_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='bio_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
