# Generated by Django 4.2.27 on 2026-05-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_biometric_bio_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometric',
            name='bio_emp',
        ),
    ]
