# Generated by Django 4.2.27 on 2026-06-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_add_barangay_employee_add_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('S', 'SINGLE'), ('M', 'MARRIED'), ('SEP', 'SEPERATED'), ('W', 'WIDOWED'), ('WDR', 'WIDOWER')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
