# Generated by Django 4.2.27 on 2026-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eo_date', models.DateField()),
                ('eo_title', models.CharField(max_length=1000)),
                ('eo_number', models.CharField(max_length=100)),
                ('eo_file', models.FileField(upload_to='./file')),
            ],
        ),
    ]
