# Generated by Django 4.2.27 on 2026-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveorder',
            name='eo_file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
