# Generated by Django 4.2.27 on 2026-06-15 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_barangay'),
        ('mpoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eo_date', models.DateField()),
                ('eo_title', models.CharField(max_length=1000)),
                ('eo_number', models.CharField(max_length=100, unique=True)),
                ('eo_file', models.FileField(blank=True, null=True, upload_to='eo/')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=50)),
                ('purok', models.CharField(blank=True, max_length=100)),
                ('incident_type', models.CharField(blank=True, max_length=100)),
                ('crime_category', models.CharField(blank=True, max_length=250)),
                ('incident_datetime', models.DateTimeField(blank=True)),
                ('date_reported', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('action_taken', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('incident_file', models.FileField(blank=True, null=True, upload_to='incident/')),
                ('barangay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barangay', to='usr.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinance_date', models.DateField()),
                ('ordinance_title', models.CharField(max_length=1000)),
                ('ordinance_number', models.CharField(max_length=100, unique=True)),
                ('ordinance_file', models.FileField(blank=True, null=True, upload_to='ordinance/')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='ViewAccess',
        ),
    ]
