# Generated by Django 4.2.27 on 2026-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoc', '0002_alter_executiveorder_eo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveorder',
            name='eo_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
