# Generated by Django 4.2.27 on 2026-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoc', '0003_alter_executiveorder_eo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinance_date', models.DateField()),
                ('ordinance_title', models.CharField(max_length=1000)),
                ('ordinance_number', models.CharField(max_length=100, unique=True)),
                ('ordinance_file', models.FileField(blank=True, null=True, upload_to='ordinance/')),
            ],
        ),
        migrations.AlterField(
            model_name='executiveorder',
            name='eo_file',
            field=models.FileField(blank=True, null=True, upload_to='eo/'),
        ),
    ]
