# Generated by Django 4.2.27 on 2026-04-30 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mpoc', '0004_ordinance_alter_executiveorder_eo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=50)),
            ],
        ),
    ]
