# Generated by Django 4.2.27 on 2026-04-30 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_barangay'),
        ('mpoc', '0005_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='barangay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barangay', to='usr.barangay'),
        ),
        migrations.AddField(
            model_name='incident',
            name='crime_category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_file',
            field=models.FileField(blank=True, null=True, upload_to='incident/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='purok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
