# Generated by Django 4.2.27 on 2026-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoc', '0006_incident_action_taken_incident_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_reported',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
